export const users = [
   {
      codigo: 1,
      nombre: "Braulio Ernesto",
      apellido: "Pacheco Nuñez",
      correo: "pacheco_1@gmail.com",
      sueldobruto: 2500,
      sueldoneto: 2150,
   },
   {
      codigo: 2,
      nombre: "Maria",
      apellido: "Salas Tinta",
      correo: "salas_2@gmail.com",
      sueldobruto: 2800,
      sueldoneto: 2300,
   },
   {
      codigo: 3,
      nombre: "Andres Pablo",
      apellido: "Quispe Suyo",
      correo: "quispe_3@gmail.com",
      sueldobruto: 5000,
      sueldoneto: 4200,
   },
   {
      codigo: 4,
      nombre: "Jose Maria",
      apellido: "Rodriguez Chacón",
      correo: "rodriguez_4@gmail.com",
      sueldobruto: 2500,
      sueldoneto: 2150,
   },
   {
      codigo: 5,
      nombre: "Pedro",
      apellido: "Cruz Ojeda",
      correo: "cruz_5@gmail.com",
      sueldobruto: 2500,
      sueldoneto: 2150,
   },
   {
      codigo: 6,
      nombre: "Agustin",
      apellido: "Paniagua Ochoa",
      correo: "paniagua_6@gmail.com",
      sueldobruto: 8000,
      sueldoneto: 7200,
   },
];
